### ISSUE TITLE
### Describe the bug

### ISSUE THREAD

**Issue by Viproscore** [Viproscore/VipeTeK#3]
### Describe the bug

why i can not deploy this SC in testnet , got max code size exceeded error , even i set runs:0 , still got "max code size exceeded" error 

### Expected Behavior

can deploy SC successfully 

_Originally posted by @ChefSnoopy in https://github.com/Uniswap/v4-core/issues/274_

**Comment by ChefSnoopy** [comment]
I tried to deploy the v4-core in testnet , but got "max code size exceeded" , how could you guys deploy this version in testnet or mainnet ?
..............................................................................................................................................
Warning: Contract code size is 27298 bytes and exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
  --> contracts/PoolManager.sol:25:1:
   |
25 | contract PoolManager is IPoolManager, Owned, NoDelegateCall, ERC1155, IERC1155Receiver {
   | ^ (Relevant source part starts here and spans across multiple lines).
